ALTER TABLE "Casino" ADD COLUMN IF NOT EXISTS "licenseInfo" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Casino" ADD COLUMN IF NOT EXISTS "regulator" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Casino" ADD COLUMN IF NOT EXISTS "payoutSummary" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Casino" ADD COLUMN IF NOT EXISTS "supportQuality" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Casino" ADD COLUMN IF NOT EXISTS "supportChannels" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Casino" ADD COLUMN IF NOT EXISTS "safetyFeatures" TEXT NOT NULL DEFAULT '';
