import type { PromoCodeInput } from "@/lib/promo-code-validation";

// External bonus-site and official-promo findings only.
// Do not put PromoGuard referral codes here. Affiliate links stay in
// config/affiliateConfig.ts and are used only for outbound registration.
export const curatedPromoCodes: PromoCodeInput[] = [
  {
    casinoSlug: "rainbet",
    code: "CSGOBETTINGS",
    label: "20% rakeback boost",
    benefitTitle: "20% rakeback available",
    benefitDescription: "External coupon reporting lists CSGOBETTINGS as a Rainbet rakeback code with recent community activity.",
    bonusType: "Rakeback",
    wageringRequirements: "Rakeback terms apply on Rainbet; confirm account eligibility before wagering.",
    conditions: "New or eligible users only. Region and campaign rules may apply.",
    requirements: "Open Rainbet, register, and enter the code where Rainbet asks for a promo or referral code.",
    source: "External bonus site",
    sourceId: "external-bonus-site",
    sourceSiteId: "wethrift-rainbet",
    isAffiliateOwned: false,
    isVerified: true,
    isActive: true,
    priority: 80,
    validFrom: "2026-05-29T00:00:00.000Z",
    region: "GLOBAL"
  },
  {
    casinoSlug: "rainbet",
    code: "BONUS50",
    label: "Deposit match up to $2,000",
    benefitTitle: "Deposit match bonus up to $2,000",
    benefitDescription: "External coupon reporting lists BONUS50 as a Rainbet deposit-match code with recent usage activity.",
    bonusType: "Deposit match",
    wageringRequirements: "Check Rainbet's current bonus terms before deposit.",
    conditions: "Minimum deposit, wagering, and market restrictions may apply.",
    requirements: "Copy the code, open Rainbet, register, and apply it before making a qualifying deposit.",
    source: "External bonus site",
    sourceId: "external-bonus-site",
    sourceSiteId: "wethrift-rainbet",
    isAffiliateOwned: false,
    isVerified: true,
    isActive: true,
    priority: 74,
    validFrom: "2026-05-29T00:00:00.000Z",
    region: "GLOBAL"
  },
  {
    casinoSlug: "rainbet",
    code: "BACK20",
    label: "20% rakeback boost",
    benefitTitle: "20% permanent rakeback boost",
    benefitDescription: "Community reports describe BACK20 as a Rainbet rakeback boost used during signup.",
    bonusType: "Rakeback",
    wageringRequirements: "Rakeback is based on Rainbet's current rakeback mechanics.",
    conditions: "Check the promo field and current terms before deposit.",
    requirements: "Copy BACK20, open Rainbet, and enter it during signup if the promo-code field appears.",
    source: "External community report",
    sourceId: "external-community",
    sourceSiteId: "reddit-rainbet-promocode",
    isAffiliateOwned: false,
    isVerified: true,
    isActive: true,
    priority: 70,
    validFrom: "2026-05-29T00:00:00.000Z",
    region: "GLOBAL"
  },
  {
    casinoSlug: "shuffle",
    code: "SHFLVIP",
    label: "200% first-deposit bonus up to $1,000",
    benefitTitle: "200% deposit bonus up to $1,000",
    benefitDescription: "External Shuffle promo pages report SHFLVIP as a new-player first-deposit code.",
    bonusType: "Deposit match",
    minDeposit: 20,
    wageringRequirements: "Wagering and eligible-game terms apply; confirm the live Shuffle terms.",
    conditions: "New players only. Minimum deposit is reported by external pages and must be verified at checkout.",
    requirements: "Copy SHFLVIP, open Shuffle, register, enter the code, then make a qualifying first deposit.",
    source: "External bonus site",
    sourceId: "external-bonus-site",
    sourceSiteId: "shufflepromocode",
    isAffiliateOwned: false,
    isVerified: true,
    isActive: true,
    priority: 85,
    validFrom: "2026-05-29T00:00:00.000Z",
    region: "GLOBAL"
  },
  {
    casinoSlug: "shuffle",
    code: "COVERS",
    label: "200% match up to $1,000",
    benefitTitle: "200% match up to $1,000",
    benefitDescription: "Covers reports COVERS as a Shuffle registration code for a welcome bonus.",
    bonusType: "Deposit match",
    wageringRequirements: "Check Shuffle's live terms before depositing.",
    conditions: "New users only. Country and promotion restrictions may apply.",
    requirements: "Copy COVERS, open Shuffle, register, and enter it during the signup flow.",
    source: "External bonus site",
    sourceId: "external-bonus-site",
    sourceSiteId: "covers-shuffle",
    isAffiliateOwned: false,
    isVerified: true,
    isActive: true,
    priority: 70,
    validFrom: "2026-05-29T00:00:00.000Z",
    region: "GLOBAL"
  },
  {
    casinoSlug: "celsius-casino",
    code: "CELSIUS550",
    label: "550% match + 250 free spins",
    benefitTitle: "550% match bonus + 250 free spins",
    benefitDescription: "External Celsius pages report CELSIUS550 as a large welcome-package code.",
    bonusType: "Deposit match + Free spins",
    wageringRequirements: "External reports mention 40x wagering; verify on Celsius before claiming.",
    conditions: "New players only. Bonus cap, deposit minimum, wagering, and country rules apply.",
    requirements: "Copy CELSIUS550, open Celsius Casino, register, and apply it in the bonus or cashier flow.",
    source: "External bonus site",
    sourceId: "external-bonus-site",
    sourceSiteId: "celsius-casino-hungary",
    isAffiliateOwned: false,
    isVerified: true,
    isActive: true,
    priority: 82,
    validFrom: "2026-05-29T00:00:00.000Z",
    region: "GLOBAL"
  },
  {
    casinoSlug: "celsius-casino",
    code: "FREESPIN50",
    label: "50 free spins",
    benefitTitle: "50 free spins",
    benefitDescription: "External Celsius pages report FREESPIN50 as a no-deposit/free-spins code.",
    bonusType: "Free spins",
    wageringRequirements: "Check Celsius free-spin terms before play.",
    conditions: "Eligibility, country, and game restrictions may apply.",
    requirements: "Copy FREESPIN50, open Celsius Casino, and enter it where bonus codes are accepted.",
    source: "External bonus site",
    sourceId: "external-bonus-site",
    sourceSiteId: "celsius-casino-hungary",
    isAffiliateOwned: false,
    isVerified: true,
    isActive: true,
    priority: 62,
    validFrom: "2026-05-29T00:00:00.000Z",
    region: "GLOBAL"
  },
  {
    casinoSlug: "bc-game",
    code: "NEWBONUS",
    label: "BC.Game welcome package",
    benefitTitle: "Welcome bonus package",
    benefitDescription: "External BC.Game promo pages report NEWBONUS as a new-player code, and BC.Game guides emphasize rotating promo-code availability.",
    bonusType: "Welcome bonus",
    wageringRequirements: "Check the live BC.Game campaign page before accepting a bonus.",
    conditions: "New users only. Bonus availability can change by region and campaign.",
    requirements: "Copy NEWBONUS, open BC.Game, register, and apply it in the signup or promo-code field.",
    source: "External bonus site",
    sourceId: "external-bonus-site",
    sourceSiteId: "whichcasino-bc-game",
    isAffiliateOwned: false,
    isVerified: true,
    isActive: true,
    priority: 78,
    validFrom: "2026-05-29T00:00:00.000Z",
    region: "GLOBAL"
  },
  {
    casinoSlug: "bitcasino",
    code: "CASIMOSPIN",
    label: "250 free spins",
    benefitTitle: "250 free spins on Oiran Dream",
    benefitDescription: "Bitcasino's support content says CASIMOSPIN can be used to claim 250 free spins on Oiran Dream when available.",
    bonusType: "Free spins",
    wageringRequirements: "Bitcasino reward terms apply; check the Rewards tab before activation.",
    conditions: "First-come, first-served and availability may change.",
    requirements: "Open Bitcasino, go to Rewards or Claim reward, enter CASIMOSPIN, then activate the reward if accepted.",
    source: "Official casino help center",
    sourceId: "official-help",
    sourceSiteId: "bitcasino-help-code",
    isAffiliateOwned: false,
    isVerified: true,
    isActive: true,
    priority: 90,
    validFrom: "2026-05-29T00:00:00.000Z",
    region: "GLOBAL"
  },
  {
    casinoSlug: "justcasino",
    code: "JUST2",
    label: "Second-deposit welcome stage",
    benefitTitle: "Second-deposit bonus code",
    benefitDescription: "External JustCasino bonus pages report JUST2 as part of a staged welcome package.",
    bonusType: "Deposit match",
    wageringRequirements: "Check JustCasino live bonus terms before deposit.",
    conditions: "Typically for the second deposit. Minimum deposit, wagering, and market rules may apply.",
    requirements: "Copy JUST2, open JustCasino, and enter it before the matching qualifying deposit.",
    source: "External bonus site",
    sourceId: "external-bonus-site",
    sourceSiteId: "justcasino-official-bonuses",
    isAffiliateOwned: false,
    isVerified: true,
    isActive: true,
    priority: 66,
    validFrom: "2026-05-29T00:00:00.000Z",
    region: "GLOBAL"
  },
  {
    casinoSlug: "justcasino",
    code: "JUST3",
    label: "Third-deposit welcome stage",
    benefitTitle: "Third-deposit bonus code",
    benefitDescription: "External JustCasino bonus pages report JUST3 as part of a staged welcome package.",
    bonusType: "Deposit match",
    wageringRequirements: "Check JustCasino live bonus terms before deposit.",
    conditions: "Typically for the third deposit. Minimum deposit, wagering, and market rules may apply.",
    requirements: "Copy JUST3, open JustCasino, and enter it before the matching qualifying deposit.",
    source: "External bonus site",
    sourceId: "external-bonus-site",
    sourceSiteId: "justcasino-official-bonuses",
    isAffiliateOwned: false,
    isVerified: true,
    isActive: true,
    priority: 65,
    validFrom: "2026-05-29T00:00:00.000Z",
    region: "GLOBAL"
  },
  {
    casinoSlug: "justcasino",
    code: "EXTRA10",
    label: "Crypto free-spins quest",
    benefitTitle: "Crypto free-spins promo",
    benefitDescription: "External JustCasino bonus pages report EXTRA10 as a crypto/free-spins quest code.",
    bonusType: "Free spins",
    wageringRequirements: "Check JustCasino live bonus terms before use.",
    conditions: "Campaign-specific. Crypto deposit and eligible-game rules may apply.",
    requirements: "Copy EXTRA10, open JustCasino, and confirm the current promotion before applying the code.",
    source: "External bonus site",
    sourceId: "external-bonus-site",
    sourceSiteId: "justcasino-official-bonuses",
    isAffiliateOwned: false,
    isVerified: true,
    isActive: true,
    priority: 58,
    validFrom: "2026-05-29T00:00:00.000Z",
    region: "GLOBAL"
  },
  {
    casinoSlug: "betpanda",
    code: "NEWBONUS",
    label: "Reported new-player bonus",
    benefitTitle: "Reported new-player bonus",
    benefitDescription: "External BetPanda pages conflict on whether NEWBONUS is required or whether the offer is no-code; try it only if a promo-code field is shown.",
    bonusType: "Welcome bonus",
    wageringRequirements: "Check BetPanda's live terms before deposit.",
    conditions: "Use only if BetPanda displays a matching promo-code field and current terms.",
    requirements: "Copy NEWBONUS, open BetPanda, and compare the live bonus field and terms before depositing.",
    source: "External bonus site",
    sourceId: "external-bonus-site",
    sourceSiteId: "coinstats-betpanda",
    isAffiliateOwned: false,
    isVerified: true,
    isActive: true,
    priority: 45,
    validFrom: "2026-05-29T00:00:00.000Z",
    region: "GLOBAL"
  },
  {
    casinoSlug: "roobet",
    code: "HELLAROO",
    label: "Reported Roobet welcome code",
    benefitTitle: "Reported welcome, cashback, and rewards code",
    benefitDescription: "External Roobet promo pages report HELLAROO as a 2026 Roobet welcome/rewards code.",
    bonusType: "Welcome bonus",
    wageringRequirements: "Check Roobet's live promo terms before depositing.",
    conditions: "New or eligible users only. Benefits may vary by region and current campaign.",
    requirements: "Copy HELLAROO, open Roobet, register, and enter it where Roobet accepts promo/referral codes.",
    source: "External bonus site",
    sourceId: "external-bonus-site",
    sourceSiteId: "jamesswan-roobet",
    isAffiliateOwned: false,
    isVerified: true,
    isActive: true,
    priority: 52,
    validFrom: "2026-05-29T00:00:00.000Z",
    region: "GLOBAL"
  },
  {
    casinoSlug: "gamdom",
    code: "GAM15",
    label: "Official Gamdom affiliate-code option",
    benefitTitle: "Eligible affiliate-code rewards",
    benefitDescription: "Gamdom's help center says users can add Gamdom's own GAM15 code or a partner code to become eligible for rewards such as promo codes, free spins, and reload bonuses.",
    bonusType: "Rewards",
    wageringRequirements: "Gamdom reward terms and eligibility rules apply.",
    conditions: "Must be added within Gamdom's eligible affiliate-code window.",
    requirements: "Copy GAM15, open Gamdom, register, and add it in the affiliate-code area if no other partner code is prefilled.",
    source: "Official casino help center",
    sourceId: "official-help",
    sourceSiteId: "gamdom-help-affiliate-code",
    isAffiliateOwned: false,
    isVerified: true,
    isActive: true,
    priority: 55,
    validFrom: "2026-05-29T00:00:00.000Z",
    region: "GLOBAL"
  }
];
